### PR TITLE
Fix budget category totals to account for refunds and reimbursements

### LINKED ISSUE #314: Bug: Budget Category totals are not taking into account category income and expenses
### General checklist

- [x] I have removed personal / sensitive data from screenshots and logs
- [x] I have searched [existing issues](https://github.com/we-promise/sure/issues?q=is:issue) and [discussions](https://github.com/we-promise/sure/discussions) to ensure this is not a duplicate issue
    
### How are you using Sure?

- [ ] I was a paying Maybe customer (hosted version)
- [ ] I use it on PikaPod, Umbrel or similar (VPS included)
- [x] I am a self-hosted user (local only)

### Self hoster checklist

_Paying, hosted users should delete this entire section._

If you are a self-hosted user, please complete all of the information below.  Issues with incomplete information will be marked as `Needs Info` to help our small team prioritize bug fixes.

- Self hosted app commit SHA (find in user menu): [enter commit sha here]
  - [X] I have confirmed that my app's commit is the latest version of Sure
- Where are you hosting?
  - [ ] Render
  - [X] Docker Compose
  - [ ] Umbrel
  - [ ] PikaPod
  - [ ] Other (please specify)

---

## Bug description

When tracking budgets that include returns or reimbursements, Sure currently does not account for negative transactions (refunds) against the original expense. This causes the budget to reflect the gross spending instead of the net spending.

For example, if a user spends $500 on clothing and later returns $200 worth of items, the budget still shows $500 spent, rather than the expected $300. This leads to inaccurate budgeting and reporting for categories like clothing or healthcare (where reimbursements are common).

This behavior also impacts real-world cases such as:
- Healthcare expenses partially reimbursed by insurance.
- Returned purchases (e.g., clothing, electronics, etc.).
- Expense categories where partial refunds or adjustments are common.

Ideally, the app should allow negative transactions to offset prior spending in the same category, or provide a clear way to record refunds that accurately adjust the category total.

### To Reproduce

1. Create a budget category (e.g. “Clothing”).
2. Add a $500 expense to that category.
3. Add a $200 refund (negative expense or income) to the same category.
4. Observe the total budget calculation for that category. 

### Expected behavior

The budget should account for refunds or reimbursements by subtracting them from total spending.
In the above example, the category total should display $300 spent, not $500.

### Screenshots and/or recordings

Image

Image

Image

Screenshots show the budget screen with the budget category of "Healthcare" having a limit of $20 to spend. The user then goes over the budget with their expense A, and then receives a reimbursement of B. This should but them back to below the limit, but no change occurs.

### PR DESCRIPTION
**Pull request by eureka0928**
## Summary

- **Budget spending now nets refunds against expenses** in the same category. Previously, refunds (negative transactions classified as income) were excluded entirely from budget calculations, causing budgets to display gross spending instead of net spending. For example, a $500 healthcare expense followed by a $200 insurance reimbursement now correctly shows $300 spent instead of $500.
- **Per-category and overall budget totals are clamped to zero** to prevent negative spending values when refunds exceed expenses in a category.
- **Subcategory double-counting is avoided** in the overall budget refund calculation by excluding subcategories whose totals are already rolled into their parent category totals.

image

### `app/models/budget.rb`
- `actual_spending`: Subtracts refunds in expense categories from the gross expense total, clamped to 0
- `budget_category_actual_spending`: Looks up both expense and income (refund) totals for the category and returns the net amount, clamped to 0
- New private method `refunds_in_expense_categories`: Sums income totals that belong to expense categories (excluding subcategories to avoid double-counting with parent totals)

### `test/models/budget_test.rb`
- Added test: refunds in an expense category are subtracted from that category's budget spending
- Added test: budget category spending does not go below zero when refunds exceed expenses

Closes #314

## Summary by CodeRabbit

* **Bug Fixes**
  * Actual spending now nets refunds against expenses, including per-category and uncategorized refunds.
  * Category spending is clamped at a minimum of zero.

* **Tests**
  * Added tests verifying refund handling, per-category netting, uncategorized refund impact, and non-negative spending.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by fury0928** [comment]
@jjmata ready for review 😉

**Comment by fury0928** [comment]
@sokie how are you?
Would you review this PR as you wrote your opinion on discord?

**Comment by jjmata** [comment]
Adding @sokie as reviewer as he might get to it before I do!

File: app/models/budget.rb [hunk 1]
```diff
@@ -155,11 +155,13 @@ def estimated_spending
...
   def actual_spending
-    expense_totals.total
+    [ expense_totals.total - refunds_in_expense_categories, 0 ].max
   end
 
   def budget_category_actual_spending(budget_category)
-    expense_totals.category_totals.find { |ct| ct.category.id == budget_category.category.id }&.total || 0
+    expense = expense_totals.category_totals.find { |ct| ct.category.id == budget_category.category.id }&.total || 0
+    refund = income_totals.category_totals.find { |ct| ct.category.id == budget_category.category.id }&.total || 0
+    [ expense - refund, 0 ].max
```
Comment (CylonN8) [inline app/models/budget.rb:165]: I tested this locally and it works as expected. The code LGTM.

One minor note: `budget_category_actual_spending` does a linear search through `category_totals` on each call, so we get O(N^2) as it's called for every budget category. Like if we have 20 categories scanning through ~20 items each time, that's 400 iterations. With 50 categories it jumps to 2,500. We could memoize a hash lookup to make it O(N), might be worth it if people have tons of categories/subcategories but probably not a big deal for now.

Comment (jjmata) [reply app/models/budget.rb:165]: OK, that needs to be fixed then.  Can you address @eureka928?

Comment (CylonN8) [reply app/models/budget.rb:165]: > OK, that needs to be fixed then. Can you address @eureka928?

I can do it if you want, that's a quick fix

**Comment by CylonN8** [comment]
There's an edge case with reimbursements across budget periods. Like if you pay $300 for a group on Jan 28th and get reimbursed $100 from one person on Jan 29th and $200 on Feb 5th January's budget shows the full $300 expense minus only the $100 refund. The $200 that comes in Feb 5th hits February's budget even though it's reimbursing a January expense.

Could be useful to let users link reimbursement transactions to the original payment. That way the reimbursements count toward the budget period of the original expense, but their actual transaction dates stay the same for cash flow tracking.

File: app/models/budget.rb (hunk 1 above)
Comment (CylonN8) [reply app/models/budget.rb:165]: @jjmata Done in https://github.com/eureka928/sure/pull/3/commits/2ae74429dfb500b0fa17c0a583a38823ab30bed7. Feel free to review it.

Comment (fury0928) [reply app/models/budget.rb:165]: This is cool, would you merge that into this PR? @CylonN8

Comment (fury0928) [reply app/models/budget.rb:165]: Let me update this PR, few mins

Comment (CylonN8) [reply app/models/budget.rb:165]: > This is cool, would you merge that into this PR? @CylonN8

I tried but I don't have permission to push to your repo, that's why I opened a PR for you to merge it.

Comment (fury0928) [reply app/models/budget.rb:165]: my PR is updated, please review @CylonN8 @jjmata

**Comment by fury0928** [comment]
@CylonN8 I updated my PR

**Comment by CylonN8** [comment]
> @CylonN8 I updated my PR

I tried it and it's working as expected IMO. @eureka928

**Comment by fury0928** [comment]
> > @CylonN8 I updated my PR
> 
> I tried it and it's working as expected IMO. @eureka928

Thank you for your review, this is ready to merge! cc: @jjmata

**Comment by jjmata** [comment]
> Could be useful to let users link reimbursement transactions to the original payment. That way the reimbursements count toward the budget period of the original expense, but their actual transaction dates stay the same for cash flow tracking.

I can only imagine how complicated that SQL statement gets that wrangles all refunds in the right time periods.  What about those Costco returns you make _months_ after purchase? 🙈  :-)

**Comment by jjmata** [comment]
Thanks for the review @CylonN8! 🙏

**Comment by sokie** [comment]
> > Could be useful to let users link reimbursement transactions to the original payment. That way the reimbursements count toward the budget period of the original expense, but their actual transaction dates stay the same for cash flow tracking.
> 
> I can only imagine how complicated that SQL statement gets that wrangles all refunds in the right time periods. What about those Costco returns you make _months_ after purchase? 🙈 :-)

That's not how it should be.  
Budget is about a period. A refund 2 months later should mean you are -50 on that budget then for that month

**Comment by jjmata** [comment]
> Budget is about a period. A refund 2 months later should mean you are -50 on that budget then for that month

I know ... that is why I was joking about it.  We both agree that the period of 1 month is arbitrary in the case @CylonN8 was describing (a refund on the 1st for a purchase on the last few days of the previous month) but it gets reeeeeally hard to codify that.  Much easier when it's a return from last quarter!

Though mentally it does go back in my "buy more toys budget" for the year when I return something. :-)
