### PR TITLE
Simplefin enhancements v2

### LINKED ISSUE #110: bug: Initial SimpleFIN account sync failures
### General checklist

- [x ] I have removed personal / sensitive data from screenshots and logs
- [ x] I have searched [existing issues](https://github.com/we-promise/sure/issues?q=is:issue) and [discussions](https://github.com/we-promise/sure/discussions) to ensure this is not a duplicate issue
    
### How are you using Sure?

- [ ] I was a paying Maybe customer (hosted version)
- [ ] I use it on PikaPod, Umbrel or similar (VPS included)
- [ x] I am a self-hosted user (local only)

### Self hoster checklist

_Paying, hosted users should delete this entire section._

If you are a self-hosted user, please complete all of the information below.  Issues with incomplete information will be marked as `Needs Info` to help our small team prioritize bug fixes.

- Self hosted app commit SHA (find in user menu): [not sure where I find this; can confirm 0.6.3 is installed]
  - [x ] I have confirmed that my app's commit is the latest version of Sure
- Where are you hosting?
  - [ ] Render
  - [x ] Docker Compose
  - [ ] Umbrel
  - [ ] PikaPod
  - [ ] Other (please specify)

---

## Bug description

I pasted my SimpleFin API key and it appeared to sync; however, no accounts were created and SimpleFin reports no attempted accesses.

### To Reproduce

I've tried multiple APIs.

Go to SimpleFin connections menu, add in API key and click Add Connection.

### Expected behavior

The accounts I have synced with SimpleFin to be created in Sure

### Screenshots and/or recordings

Image

Image

### PR DESCRIPTION
**Pull request by luckyPipewrench**
Ports and expands #254 ideas to the new Providers Factory from #250, making SimpleFin more reliable, user-friendly, and secure. Addresses duplicate transactions (#110) and adds tools for common pain points like flaky syncs and account relinks. Builds on multi-provider support with guards to prevent "Other accounts" leaks.
Key Changes

Provider Framework Integration:

SimpleFin via Provider::SimplefinAdapter with centralized persistence in Account::ProviderImportAdapter.
Multi-provider ready: Auto-maintain AccountProvider links; guard against duplicates per type.

Sync Engine Enhancements:

Chunked first-sync (60-day with discovery) + 7-day buffer for regulars to respect Bridge limits.
Per-account error skipping with sync_stats; no full aborts.
Rate-limit detection (rate_limited_at timestamp) with UI feedback.
Balances-only mode: Quick refresh (updates balances/last_synced_at without transactions) via param; new controller action and dev-only card button (retainable in prod).
Optimized the balances import to run in the background for snappier UI

Transaction Dedup/Merging:

Matching: external_id + source → FITID → composite (±7d date, ±$0.01 amount, normalized names).
Pending→posted merges: Update existing entry, set transactions.was_merged = true, add note.
UI: Subtle "Merged" badge with tooltip.

UI Polish:

SimpleFin card badges: Unlinked/Skipped/Total; Rate-limited (time-ago tooltip).
Categorized error tooltips (auth/api/network/other) with samples.
"View errors" modal: Per-account lists + category counts.
Auto-relink on re-add (heuristics: last4/balance/name) to prevent orphans.
Manual relink modal: "Link existing accounts" button lists pairs; applies with dupe cleanup (skip/delete entries/holdings), data migration, and redundant account removal.

Rake Tasks & Utilities:

sure:simplefin:encrypt_access_urls: Idempotent backfill (dry-run/batch/limit, credentials-gated).
sure:backfill_was_merged: Heuristic for legacy pendings (dry-run/live).
Fixed private method crash; safe badge rendering.

Tests: 24+ green for adapters/import/UI; 100+ assertions covering chunking/skips/dedup/merges/relinks.

Impact

Smoother onboarding/syncs, fewer dupes from pendings/relinks.
Better handles Bridge quirks (quotas, errors) without overwhelming UI.
Future-proof: Aligns with #250's API layer TODO; extensible for extras like custom currencies.

Requesting reviews from @sokie and @jjmata. Fixes #110, #303  ; closes #254 (draft).

## Summary by CodeRabbit

* **New Features**
  * Added balances-only sync functionality for faster per-account balance updates.
  * Added error viewing modal to display latest SimpleFIN sync errors.
  * Enhanced transaction details display with provider metadata and additional fields.
  * Improved account linking workflows with modal-based relink flow and duplicate detection.
  * Added day-change tracking for holdings.

* **Bug Fixes**
  * Improved race condition handling in automatic transfer matching.
  * Enhanced duplicate account detection and error categorization during syncs.

---

> [!NOTE]
> Adds SimpleFin relink and balances-only sync, improves dedup/merge and pending→posted handling with richer UI/status and metadata, plus DB/index changes and rake utilities.
> 
> - **SimpleFin backend & sync**:
>   - Add balances-only sync path and stats via `SimplefinItem::Importer#import_balances_only` and `SimplefinItem::Syncer` (rate-limit detection, per-account error buckets, API request tracking).
>   - Enhance first/regular sync (chunked discovery, pending include, unbounded discovery) and snapshot persistence; guard/cleanup via `dedup_simplefin_accounts!` and `merge_duplicate_provider_accounts!`.
>   - New relink flow: compute candidates, modal UI, and `apply_relink` to migrate entries/holdings and move provider links; auto-open via `auto_relink_controller.js` and `open_relink_for`.
>   - Safer deletion: `SimplefinItem::Unlinker` unlinks provider links before destroy.
> - **Transactions & holdings**:
>   - Strengthen de‑dupe/merge in `Account::ProviderImportAdapter#import_transaction` (external_id→FITID→composite; mark `transactions.was_merged`; persist `transaction.extra`; notes, date heuristics by account type).
>   - Add holdings day-change display and improved SimpleFin holdings processing (crypto symbol namespace, robust field fallbacks).
>   - Improve auto transfer matching idempotency (`find_or_create_by!` with `RecordNotUnique` rescue).
> - **Controllers, views, routes**:
>   - `SimplefinItemsController`: new actions `balances`, `errors`, `relink`, `apply_relink`; enhanced `create/update/destroy/setup_accounts` flows.
>   - UI: SimpleFin card badges (unlinked/skipped/total, rate-limited), sync summary panel, errors modal, relink modal; auto-open relink; transaction merged badge and "Additional details" panel.
>   - Routes for new actions; helper `simplefin_error_tooltip`.
> - **Data & migrations**:
>   - Add `transactions.was_merged` and `transactions.extra` (GIN index).
>   - Add `ON DELETE CASCADE` FKs for `entries`, `holdings`, `account_providers`; schema updated.
>   - Minor config: `config/database.yml` `username` key.
> - **Rake tasks**:
>   - Backfills/fixes: `sure:backfill_was_merged`, `sure:simplefin:fix_was_merged`, `sure:simplefin:backfill_extra`, holdings backfill, unlink, encrypt access URLs, debug and cleanup utilities.
> - **Tests**:
>   - Expanded coverage for relink, dedupe, balances-only, pending→posted merge, extra metadata, holdings deletion rules, turbo responses.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e84ea59efaecf1d869f7106446aa930f8f431573. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/models/simplefin_account/processor.rb [hunk 1]
```diff
@@ -9,18 +9,96 @@ def initialize(simplefin_account)
...
     process_investments
     process_liabilities
   end
 
   private
 
+    # Attempt to auto-relink this SimpleFin upstream account to an existing manual Account
+    # that has the same normalized name. This helps avoid duplicates under "Other accounts"
+    # when users delete/re-link a SimpleFin connection.
+    def auto_relink_existing_manual_account
```
Comment (sokie) [inline app/models/simplefin_account/processor.rb]: this is also way too error prone, it tries to auto link simplefin with any manual account based on heuristics
We should not do this, instead we should add a button to link existing manual accounts with simplefin.
It should never happen automatically

File: app/models/account/provider_import_adapter.rb [hunk 2]
```diff
@@ -15,18 +15,44 @@ def initialize(account)
...
+        entry = composite_match(source: source, name: name, amount: amount, date: date, window_days: window_days)
+        if entry
+          # Only flag was_merged when it looks like true pending→posted progression
+          if entry.entryable.is_a?(Transaction) && pending_merge?(existing_entry: entry, incoming_date: to_date(date), incoming_pending: pending, incoming_posted_date: posted_date, incoming_transacted_date: transacted_date, window_days: window_days, incoming_amount: amount)
+            if entry.entryable.respond_to?(:was_merged=)
+              entry.entryable.was_merged = true
+            end
+          end
+          # Always update external_id so future syncs dedup by provider id
+          entry.external_id = external_id
```
Comment (sokie) [inline app/models/account/provider_import_adapter.rb]: nice one! this is correct

File: app/models/account/provider_import_adapter.rb [hunk 3]
```diff
@@ -15,18 +15,44 @@ def initialize(account)
...
-        e.entryable = Transaction.new
+      # 1) Prefer exact match by external_id + source
+      entry = account.entries.find_by(external_id: external_id, source: source)
+
+      # 2) FITID fallback (when provided)
+      if entry.nil? && fitid.present?
+        entry = account.entries.find_by(external_id: fitid, source: source)
+      end
+
+      # 3) Composite match (date window by account type, amount ≤ 0.01, normalized name, same sign)
```
Comment (sokie) [inline app/models/account/provider_import_adapter.rb]: this is too broad for a financial app. I'm not sure if SimpleFIN posts pending transactions too, other providers generally don't, so time window should not be neccesary.
Amount heuristics are also not correct, unless a user manually added an entry and made a mistake, even a 1 cent different should NEVER happen.

Comment (luckyPipewrench) [reply app/models/account/provider_import_adapter.rb]: Yeah, you're right, auto-linking based on names and stuff wind up grabbing the wrong account and cause issues. Better to keep it manual. I'll swap it out for a button in the relink modal where users can pick and confirm, using the heuristics just as suggestions. Fixing that up now.

File: app/models/simplefin_account/processor.rb (hunk 1 above)
Comment (luckyPipewrench) [reply app/models/simplefin_account/processor.rb]: Good point on this being too loose, I didn't realize SimpleFin skips pendings like the others, so exact date and amount makes way more sense to avoid false matches. I'll drop the window and tolerance for stricter checks. If we need some flex for user errors down the line, we could add a toggle later. Updating it shortly.

**Comment by luckyPipewrench** [comment]
Rebased on main

**Comment by jjmata** [comment]
How do you guys feel about the remaining bot-comments @luckyPipewrench and @sokie?

**Comment by sokie** [comment]
> How do you guys feel about the remaining bot-comments @luckyPipewrench and @sokie?

I am waiting for @luckyPipewrench to finish all the changes and once ready I'll do a proper reveiw

**Comment by luckyPipewrench** [comment]
> > How do you guys feel about the remaining bot-comments @luckyPipewrench and @sokie?
> 
> I am waiting for @luckyPipewrench to finish all the changes and once ready I'll do a proper reveiw

@sokie Sorry, my discord has limited access for a couple days,,,, But thanks for the context. Sorry I missed your DM before pinging you for review! #268 is awesome. De-dup should be strict enough now, linking is manual-only, user selects via check boxes in modal, not auto. Will tighten if needed. On generalization, the modal is simplefin-specific for now, planning to make it provider-agnostic in a follow up later unless you think I should change it before it merges.

**Comment by sokie** [comment]
> > > How do you guys feel about the remaining bot-comments @luckyPipewrench and @sokie?
> > 
> > 
> > I am waiting for @luckyPipewrench to finish all the changes and once ready I'll do a proper reveiw
> 
> @sokie Sorry, my discord has limited access for a couple days,,,, But thanks for the context. Sorry I missed your DM before pinging you for review! #268 is awesome. De-dup should be strict enough now, linking is manual-only, user selects via check boxes in modal, not auto. Will tighten if needed. On generalization, the modal is simplefin-specific for now, planning to make it provider-agnostic in a follow up later unless you think I should change it before it merges.

Sounds good!
First pass i did with the previous feedback, tbh i think this is in a really good place already now.
I'll do a thorough pass tomorrow and leave a review.
PS: resolve all the fixed items from Coderabbit so we know what is left or not.

File: app/models/account/provider_import_adapter.rb [hunk 4]
```diff
@@ -15,8 +15,10 @@ def initialize(account)
   # @param source [String] Provider name (e.g., "plaid", "simplefin")
   # @param category_id [Integer, nil] Optional category ID
   # @param merchant [Merchant, nil] Optional merchant object
+  # @param notes [String, nil] Optional transaction notes/memo
+  # @param extra [Hash, nil] Optional provider-specific metadata to merge into transaction.extra
   # @return [Entry] The created or updated entry
-  def import_transaction(external_id:, amount:, currency:, date:, name:, source:, category_id: nil, merchant: nil)
+  def import_transaction(external_id:, amount:, currency:, date:, name:, source:, category_id: nil, merchant: nil, notes: nil, extra: nil)
```
Comment (sokie) [inline app/models/account/provider_import_adapter.rb:21]: good addition!

File: app/models/simplefin_account/investments/holdings_processor.rb [hunk 5]
```diff
@@ -5,38 +5,69 @@ def initialize(simplefin_account)
...
     holdings_data.each do |simplefin_holding|
       begin
-        symbol = simplefin_holding["symbol"]
-        holding_id = simplefin_holding["id"]
+        data = simplefin_holding.with_indifferent_access
+        symbol = data[:symbol]
+        holding_id = data[:id]
 
-        next unless symbol.present? && holding_id.present?
+        if ENV["SURE_LOG_SIMPLEFIN_HOLDINGS"].present?
```
Comment (sokie) [inline app/models/simplefin_account/investments/holdings_processor.rb]: @luckyPipewrench should this be just changed to a debug log?

File: app/models/simplefin_account/investments/holdings_processor.rb [hunk 6]
```diff
@@ -69,8 +104,17 @@ def holdings_data
     end
 
     def resolve_security(symbol, description)
+      # Normalize crypto tickers to a distinct namespace so they don't collide with equities
```
Comment (sokie) [inline app/models/simplefin_account/investments/holdings_processor.rb:95]: I don't know how many people use this, but we'll probably have to standardize/expand this in the future.

File: config/database.yml [hunk 7]
```diff
@@ -4,7 +4,7 @@ default: &default
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
   host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
   port: <%= ENV.fetch("DB_PORT") { "5432" } %>
-  user: <%= ENV.fetch("POSTGRES_USER") { nil } %>
+  username: <%= ENV.fetch("POSTGRES_USER") { nil } %>
```
Comment (sokie) [inline config/database.yml]: @luckyPipewrench why this change?

File: app/views/transactions/_transaction.html.erb [hunk 8]
```diff
@@ -68,6 +68,10 @@
                     <% if transaction.transfer.present? %>
                       <%= render "transactions/transfer_match", transaction: transaction %>
                     <% end %>
+
+                    <% if transaction.respond_to?(:was_merged) && transaction.was_merged %>
```
Comment (sokie) [inline app/views/transactions/_transaction.html.erb]: is this still applicable? @luckyPipewrench

File: app/models/simplefin_item.rb [hunk 9]
```diff
@@ -148,6 +157,122 @@ def institution_summary
...
+        end
+      end
+    end
+
+    { merged_accounts: merged_accounts, moved_entries: moved_entries, moved_holdings: moved_holdings, legacy_repointed: legacy_repointed, removed_providers: removed_providers, deleted_simplefin_accounts: deleted_sfas }
+  end
+
+  # Merge duplicate provider-linked Accounts that point to the same SimpleFin account (via AccountProvider).
+  # Keeps the account with more entries (or newest), moves entries/holdings from duplicates, and deletes them.
+  def merge_duplicate_provider_accounts!
```
Comment (sokie) [inline app/models/simplefin_item.rb]: I think this is made too complex.
I think the flow should be kept simple:
- Allow to unlink accounts ( from any provider )
- If we link again, we do usual dedup. 
Rest is kept simpler.

File: app/controllers/concerns/simplefin_items/relink_helpers.rb [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+            .count
+      end
+
+      def normalize_name(str)
+        s = str.to_s.downcase.strip
+        return s if s.empty?
+        s.gsub(NAME_NORM_RE, " ")
+      end
+
+      def compute_relink_candidates
```
Comment (sokie) [inline app/controllers/concerns/simplefin_items/relink_helpers.rb]: I also think we can keep this simpler.
For all normal ( unlinked ) accounts, we should show a manual link button, and just show all SimpleFIN available accounts ( with maybe already linked accounts grayed out )
See screenshot

Image

File: app/models/simplefin_item.rb [hunk 11]
```diff
@@ -148,6 +157,122 @@ def institution_summary
     end
   end
 
+  # Collapse duplicate SimpleFin accounts for the same upstream account_id within this item.
+  # Keeps one record per upstream account_id (prefer the one linked to an Account; else newest),
+  # migrates provider links and legacy FKs to the keeper, and deletes extras.
+  def dedup_simplefin_accounts!
```
Comment (sokie) [inline app/models/simplefin_item.rb]: @luckyPipewrench why would this be ever needed?
If we are talking upstream accounts:
- we should take care of it with the unlin, relink flow

If we are talking about standards accounts:
- we might create a feature to merge 2 existing accounts, incase someone merged/created 2 local accounts from different providers on the same "logical" account.

File: app/models/simplefin_account/investments/holdings_processor.rb (hunk 5 above)
Comment (luckyPipewrench) [reply app/models/simplefin_account/investments/holdings_processor.rb]: yeah, the ENV was a quick hack while working. I'll swap it in the next push.

File: config/database.yml (hunk 7 above)
Comment (luckyPipewrench) [reply config/database.yml]: This was a quick fix I added while debugging some local db connection issues, I'll clean it up.

File: app/models/simplefin_item.rb (hunk 9 above)
Comment (luckyPipewrench) [reply app/models/simplefin_item.rb]: Agreed, this got over-complicated from my dev duplicate woes. I like the unlink > relink with dedup flow to keep things simpler.

File: app/models/simplefin_item.rb (hunk 11 above)
Comment (luckyPipewrench) [reply app/models/simplefin_item.rb]: Yeah, this was probably overkill from my local testing loops creating extras. If unlink/relink covers upstream dupes, and we add a general account merge later for locals, I can drop this.

Comment (sokie) [reply app/models/simplefin_item.rb]: Sounds great!

File: app/controllers/concerns/self_hostable.rb [hunk 12]
```diff
@@ -9,6 +9,12 @@ module SelfHostable
 
   private
     def self_hosted?
+      # Respect per-request ENV overrides in test/development environments
```
Comment (sokie) [inline app/controllers/concerns/self_hostable.rb]: @luckyPipewrench what is the use-case for this?

**Review by sokie — APPROVED** [review]
LGTM

File: app/controllers/concerns/self_hostable.rb (hunk 12 above)
Comment (luckyPipewrench) [reply app/controllers/concerns/self_hostable.rb]: It really doesn't have a real use-case here, it can be removed.. I tossed it in from an AI suggestion while debugging tests, but it's just unnecessary fluff since we don't do managed mode in Sure.

Comment (sokie) [inline app/controllers/concerns/self_hostable.rb]: @luckyPipewrench what is this used for?

Comment (luckyPipewrench) [reply app/controllers/concerns/self_hostable.rb]: doesn't have a real use-case here. I tossed it in from an AI suggestion while debugging tests, but it's just unnecessary fluff since we don't do managed mode in Sure. Removing it now.

**Comment by luckyPipewrench** [comment]
@jjmata lemme know whatcha think...

**Comment by jjmata** [comment]
> @jjmata lemme know whatcha think...

@sokie is going to give this one final look tomorrow, you are done right @luckyPipewrench?  Let's move any other work to future PRs so we can close this one up.

**Comment by luckyPipewrench** [comment]
> > @jjmata lemme know whatcha think...
> 
> @sokie is going to give this one final look tomorrow, you are done right @luckyPipewrench? Let's move any other work to future PRs so we can close this one up.

Sounds good to me, it's done.

File: app/controllers/concerns/simplefin_items/relink_helpers.rb
Comment (sokie) [inline app/controllers/concerns/simplefin_items/relink_helpers.rb:1]: @luckyPipewrench can I ask you if we can keep the unlinking/relinking stuff out of this PR?
and maybe use the unified way for ALL providers in https://github.com/we-promise/sure/pull/318 ?

File: app/helpers/transactions_helper.rb [hunk 13]
```diff
@@ -18,4 +18,61 @@ def get_transaction_search_filter_partial_path(filter)
   def get_default_transaction_search_filter
     transaction_search_filters[0]
   end
+
+  # ---- Transaction extra details helpers ----
```
Comment (sokie) [inline app/helpers/transactions_helper.rb:22]: is this for debug, or?

File: app/javascript/controllers/auto_relink_controller.js
Comment (sokie) [inline app/javascript/controllers/auto_relink_controller.js:1]: ditto as above, can we maybe keep this out then, as we move to unify stuff across providers?

File: app/javascript/controllers/auto_submit_controller.js
Comment (sokie) [inline app/javascript/controllers/auto_submit_controller.js:1]: what is the need of this controller vs existing Turbo form?

File: app/models/simplefin_item/unlinking.rb
Comment (sokie) [inline app/models/simplefin_item/unlinking.rb:1]: Ditto as above, we can keep this class tough and reuse it in the providers own unlink method, since it has support for holdings unlinking.

File: db/migrate/20251029015700_add_was_merged_to_transactions.rb
Comment (sokie) [inline db/migrate/20251029015700_add_was_merged_to_transactions.rb:1]: @luckyPipewrench we don't use this anymore right? we should delete this file.

File: app/controllers/concerns/simplefin_items/relink_helpers.rb
Comment (luckyPipewrench) [reply app/controllers/concerns/simplefin_items/relink_helpers.rb:1]: We can, I like the way you handled it better. I suppose we'll let 318 merge and then rework it.

File: app/helpers/transactions_helper.rb (hunk 13 above)
Comment (luckyPipewrench) [reply app/helpers/transactions_helper.rb:22]: These helpers are used in the transactions search menu and the transaction details page. Specifically:
 _menu.html.erb uses `get_default_transaction_search_filter` for the initial tab
 show.html.erb uses `build_transaction_extra_details`

File: app/javascript/controllers/auto_submit_controller.js
Comment (luckyPipewrench) [reply app/javascript/controllers/auto_submit_controller.js:1]: It's redundant and can go also.

File: db/migrate/20251029015700_add_was_merged_to_transactions.rb
Comment (jjmata) [reply db/migrate/20251029015700_add_was_merged_to_transactions.rb:1]: Took care of this small thing.

File: app/javascript/controllers/auto_submit_controller.js
Comment (jjmata) [reply app/javascript/controllers/auto_submit_controller.js:1]: Done!

File: app/controllers/concerns/simplefin_items/relink_helpers.rb
Comment (jjmata) [reply app/controllers/concerns/simplefin_items/relink_helpers.rb:1]: OK ... so 318 is almost ready.  I tested it locally and there's only a couple of CR comments left.  When you have that one @sokie will merge ASAP so @luckyPipewrench can finish here! We're almost there.

**Review by sokie — CHANGES_REQUESTED** [review]
Connection and stability is really good, tested it and it works great.
Unfortunately I found a bug with the linking feature.
It seems I can link accounts from "Other" to SimpleFIN accounts that are already linked and synced.
This means I end up getting multiple acocunts linked to the same remote SimpleFIn account ( screenshot 2 ).
In the Lunch Flow link feature, I used to check for accounts that are already linked, and not show those, that functionality seems to also be broken now. Also when I create accounts. 


Image

Image
