### PR TITLE
fix: allow high precision for security prices in trade forms (to solve #1323)

### LINKED ISSUE #1323: Bug: model_price field limited to 2 decimal places in investment transaction form
### General checklist

- [X] I have removed personal / sensitive data from screenshots and logs
- [x] I have searched [existing issues](https://github.com/we-promise/sure/issues?q=is:issue) and [discussions](https://github.com/we-promise/sure/discussions) to ensure this is not a duplicate issue
    
### How are you using Sure?

- [ ] I was a paying Maybe customer (hosted version)
- [ ] I use it on PikaPod, Umbrel or similar (VPS included)
- [x] I am a self-hosted user (local only)

### Self hoster checklist

- Self hosted app commit SHA (find in user menu): [91b7905]
  - [x] I have confirmed that my app's commit is the latest version of Sure
- Where are you hosting?
  - [ ] Render
  - [x] Docker Compose
  - [ ] Umbrel
  - [ ] PikaPod
  - [ ] Other (please specify)

---

## Bug description

The model_price field in the "Add transaction" form for an investment account is limited to a step of 0.01.

However, in real-world financial markets, asset prices (stocks, ETFs, crypto, etc.) can have more precision (commonly 3 or 4 decimal places, sometimes more).

This restriction prevents users from entering accurate transaction prices and may lead to rounding errors or incorrect portfolio tracking.

### To Reproduce

1. Go to an investment account
2. Click on "Add transaction"
3. Locate the model_price input field
4. Try to enter a value with more than 2 decimal places (e.g. 123.4567)
5. Observe that the input is either rounded or blocked due to the step=0.01 constraint

### Expected behavior

The model_price field should allow higher precision values.

Possible fixes:
- Remove the step restriction entirely, or
- Increase precision (e.g. step=0.0001)

This would allow users to input realistic market prices without losing accuracy.

### PR DESCRIPTION
**Pull request by boul2gom**
- Updated money_field_controller.js to respect custom precision and step values, preventing them from being overwritten by currency defaults.
- Modified _money_field.html.erb to pass precision and step options to the Stimulus controller.
- Updated convert_to_trade.html.erb to use step: 'any' for the price field to support maximum precision.

> Resolve #1323 

## Summary by CodeRabbit

* **New Features**
  * Currency input fields can be configured with custom precision and decimal step values via controller-provided settings, improving formatting and input behavior.
  * The currency symbol and numeric formatting now reflect configured currency metadata.
  * Price input in the trade conversion form now accepts flexible decimal increments ("any") for greater input flexibility.

* **Bug Fixes**
  * Network/fetch errors during currency updates are now caught and logged to prevent unhandled promise rejections.

### CODE REVIEW

**Comment by boul2gom** [comment]
The unquoted HTML data attributes is fixed, by using the rails tag. The suggestion about simplifying step validation logic won't be implemented, because it's not relevant and Stimulus does not handle `hasStepValue` properly. The no-op value restore in `money_field` was removed.
Finally, the nit issues is due to the formatter itself, so I think its good to keep it.

File: app/javascript/controllers/money_field_controller.js [hunk 1]
```diff
@@ -1,30 +1,45 @@
...
 
   handleCurrencyChange(e) {
     const selectedCurrency = e.target.value;
     this.updateAmount(selectedCurrency);
   }
 
   updateAmount(currency) {
-    new CurrenciesService().get(currency).then((currency) => {
-      this.amountTarget.step = currency.step;
+    new CurrenciesService().get(currency).then((currencyData) => {
```
[the remark this answers is not in the document]
Comment (boul2gom) [reply app/javascript/controllers/money_field_controller.js:23]: This race condition is now fixed.

File: app/javascript/controllers/money_field_controller.js [hunk 2]
```diff
@@ -1,30 +1,51 @@
...
+              : currencyData.default_precision;
+          this.amountTarget.value = parsedAmount.toFixed(precision);
         }
       }
 
-      this.symbolTarget.innerText = currency.symbol;
+      this.symbolTarget.innerText = currencyData.symbol;
+    }).catch((error) => {
+      if (requestId !== this.requestSequence) return;
+      console.error("Failed to fetch currency data for", currency, error);
```
Comment (jjmata) [inline app/javascript/controllers/money_field_controller.js]: This is something I always feel weird about ... we make very litle use of `console.log(...)` for client-side error messaging, should we?  I say we either eliminate it completely or start being consistent about giving useful messages there so people don't have to dig all the way to the Rails console.

Thoughts @sokie?

Comment (boul2gom) [reply app/javascript/controllers/money_field_controller.js]: Should I use the flash `notice` and `alert` functions ?

Comment (jjmata) [reply app/javascript/controllers/money_field_controller.js]: > Should I use the flash `notice` and `alert` functions ?

Interesting.  I was actually thinking the opposite (as in: is it worth reporting?) but you are right that might be a good thing to make the user aware of.

Have you been running with this patch/PR for a while? How common is that error? Could the user do anything to fix it? No sense in reporting an error so prominently if the user cannot act / fix it.

Comment (boul2gom) [reply app/javascript/controllers/money_field_controller.js]: 1. I haven't actually encountered this error while testing the PR.
2. It should be extremely rare, because just fetches a local JSON route. It would essentially only fail if the user loses their internet connection right when they select a new currency, or if the server goes down.
3. The user can't really fix it other than toggling the select again if it was a temporary network drop. If it fails, the only consequence is that the currency symbol and step formatting won't update visually for that field.

I'll remove this log
